#!/bin/bash
apt-get update -qq && apt-get install -y \
libbtrfs-dev \
git \
libassuan-dev \
libglib2.0-dev \
libc6-dev \
libgpgme-dev \
libgpg-error-dev \
libseccomp-dev \
libsystemd-dev \
libselinux1-dev \
pkg-config \
go-md2man \
libudev-dev \
software-properties-common \
gcc \
make
runc --version
